In [119]:
import pandas as pd
import matplotlib.pyplot as plt

In [120]:
vni = pd.read_csv(r'..\data\Dữ liệu Lịch sử VN Index.csv')
gold = pd.read_csv(r'..\data\gold_data.csv')
btc_usd = pd.read_csv(r'..\data\BTC USD.csv')
usd_vnd = pd.read_csv(r'..\data\USD VND.csv')

In [121]:
vni.head(5)

         Ngày  Lần cuối        Mở       Cao      Thấp       KL % Thay đổi
0  25/05/2026  1,886.05  1,866.46  1,891.26  1,859.31  702.58M      0.48%
1  22/05/2026  1,877.13  1,896.89  1,898.80  1,856.08  650.65M     -1.04%
2  21/05/2026  1,896.89  1,913.23  1,923.21  1,886.62  562.76M     -0.85%
3  20/05/2026  1,913.23  1,912.93  1,919.39  1,859.22    1.08B      0.02%
4  19/05/2026  1,912.93  1,927.94  1,935.07  1,902.20  904.32M     -0.78%

### vn-index

In [122]:
vni.info()

<class 'pandas.DataFrame'>
RangeIndex: 2840 entries, 0 to 2839
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Ngày        2840 non-null   str
 1   Lần cuối    2840 non-null   str
 2   Mở          2840 non-null   str
 3   Cao         2840 non-null   str
 4   Thấp        2840 non-null   str
 5   KL          2840 non-null   str
 6   % Thay đổi  2840 non-null   str
dtypes: str(7)
memory usage: 155.4 KB

In [123]:
vni['Ngày'] = pd.to_datetime(vni['Ngày'], format='%d/%m/%Y')

In [124]:
# convert data type of 'Lần cuối' column to float
vni['Lần cuối'] = vni['Lần cuối'].str.replace(',', '').astype(float)

### gold

In [125]:
gold.head(5)

  standard_time    mua    ban
0    2015-01-01  34.95  35.15
1    2015-01-04  35.12  35.20
2    2015-01-06  34.87  34.93
3    2015-01-07  34.34  34.42
4    2015-01-08  32.98  33.12

In [126]:
gold.info()

<class 'pandas.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   standard_time  2920 non-null   str
 1   mua            2920 non-null   float64
 2   ban            2920 non-null   float64
dtypes: float64(2), str(1)
memory usage: 68.6 KB

In [127]:
gold['standard_time'] = pd.to_datetime(gold['standard_time'], format='%Y-%m-%d')

In [128]:
gold.duplicated().sum()

np.int64(0)

In [129]:
gold['price_mean'] = (gold['mua'] + gold['ban']) / 2

In [130]:
gold.head(5)

  standard_time    mua    ban  price_mean
0    2015-01-01  34.95  35.15       35.05
1    2015-01-04  35.12  35.20       35.16
2    2015-01-06  34.87  34.93       34.90
3    2015-01-07  34.34  34.42       34.38
4    2015-01-08  32.98  33.12       33.05

In [131]:
gold['standard_time'].max()

Timestamp('2025-03-22 00:00:00')

### Bitcoin

In [132]:
btc_usd.head(5)

         Ngày Lần cuối     Mở    Cao   Thấp     KL  % Thay đổi
0  01/01/2015    313.9  317.5  317.5  312.9  0.93K       -0.99
1  02/01/2015    315.1  313.6  316.0  313.0  1.32K        0.40
2  03/01/2015    282.0  314.8  314.8  282.0  1.30K      -10.51
3  04/01/2015    258.8  282.0  288.9  258.8  2.38K       -8.23
4  05/01/2015    273.2  261.0  276.5  260.5  2.68K        5.57

In [133]:
btc_usd.info()

<class 'pandas.DataFrame'>
RangeIndex: 4063 entries, 0 to 4062
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Ngày        4061 non-null   str
 1   Lần cuối    4062 non-null   str
 2   Mở          4062 non-null   str
 3   Cao         4062 non-null   str
 4   Thấp        4062 non-null   str
 5   KL          4062 non-null   str
 6   % Thay đổi  4061 non-null   float64
dtypes: float64(1), str(6)
memory usage: 222.3 KB

In [134]:
btc_usd['Ngày'] = pd.to_datetime(btc_usd['Ngày'], format='%d/%m/%Y')

In [135]:
btc_usd['Lần cuối'] = btc_usd['Lần cuối'].str.replace(r'[^\d.]', '', regex=True).astype(float)

In [136]:
btc_usd['Lần cuối'].describe()

count      4062.000000
mean      28222.631930
std       32220.363561
min         183.000000
25%        3815.125000
50%       11516.000000
75%       43807.000000
max      126110.000000
Name: Lần cuối, dtype: float64

In [137]:
usd_vnd.head(5)

         Ngày  Lần cuối        Mở       Cao      Thấp % Thay đổi
0  01/01/2015  21,370.0  21,370.0  21,370.0  21,370.0       0.00
1  02/01/2015  21,370.0  21,387.5  21,387.5  21,387.5       0.00
2  05/01/2015  21,370.0  21,405.0  21,420.0  21,387.5       0.00
3  06/01/2015  21,420.0  21,387.5  21,439.0  21,385.0       0.23
4  07/01/2015  21,420.0  21,436.5  21,525.0  21,411.5       0.00

In [138]:
usd_vnd.info()

<class 'pandas.DataFrame'>
RangeIndex: 2906 entries, 0 to 2905
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Ngày        2904 non-null   str
 1   Lần cuối    2905 non-null   str
 2   Mở          2905 non-null   str
 3   Cao         2905 non-null   str
 4   Thấp        2905 non-null   str
 5   % Thay đổi  2905 non-null   str
dtypes: str(6)
memory usage: 136.3 KB

In [139]:
usd_vnd['Ngày'] = pd.to_datetime(usd_vnd['Ngày'], format='%d/%m/%Y')

In [140]:
usd_vnd.duplicated().sum()

np.int64(0)

In [141]:
usd_vnd['Lần cuối'] = usd_vnd['Lần cuối'].str.replace(r'[^\d.]', '', regex=True).astype(float)

In [142]:
usd_vnd['Lần cuối'].describe()

count     2905.000000
mean     23455.336661
std       1203.295662
min      21115.000000
25%      22715.000000
50%      23183.000000
75%      23725.000000
max      26457.000000
Name: Lần cuối, dtype: float64

In [143]:
# add usd_vnd column to btc_usd dataframe
btc_usd = btc_usd.merge(usd_vnd[['Ngày', 'Lần cuối']], on='Ngày', how='left', suffixes=('', '_USD_VND'))

In [144]:
btc_usd.head(5)

,Ngày,Lần cuối,Mở,Cao,Thấp,KL,% Thay đổi,Lần cuối_USD_VND
0,2015-01-01,313.9,317.5,317.5,312.9,0.93K,-0.99,21370.0
1,2015-01-02,315.1,313.6,316.0,313.0,1.32K,0.40,21370.0
2,2015-01-03,282.0,314.8,314.8,282.0,1.30K,-10.51,NaN
3,2015-01-04,258.8,282.0,288.9,258.8,2.38K,-8.23,NaN
4,2015-01-05,273.2,261.0,276.5,260.5,2.68K,5.57,21370.0

### Merge to one dataframe

In [145]:
vni['Ngày'].min(), vni['Ngày'].max()

(Timestamp('2015-01-05 00:00:00'), Timestamp('2026-05-25 00:00:00'))

In [146]:
vni.head(5)

        Ngày  Lần cuối        Mở       Cao      Thấp       KL % Thay đổi
0 2026-05-25   1886.05  1,866.46  1,891.26  1,859.31  702.58M      0.48%
1 2026-05-22   1877.13  1,896.89  1,898.80  1,856.08  650.65M     -1.04%
2 2026-05-21   1896.89  1,913.23  1,923.21  1,886.62  562.76M     -0.85%
3 2026-05-20   1913.23  1,912.93  1,919.39  1,859.22    1.08B      0.02%
4 2026-05-19   1912.93  1,927.94  1,935.07  1,902.20  904.32M     -0.78%

In [147]:
btc_usd.head(5)

,Ngày,Lần cuối,Mở,Cao,Thấp,KL,% Thay đổi,Lần cuối_USD_VND
0,2015-01-01,313.9,317.5,317.5,312.9,0.93K,-0.99,21370.0
1,2015-01-02,315.1,313.6,316.0,313.0,1.32K,0.40,21370.0
2,2015-01-03,282.0,314.8,314.8,282.0,1.30K,-10.51,NaN
3,2015-01-04,258.8,282.0,288.9,258.8,2.38K,-8.23,NaN
4,2015-01-05,273.2,261.0,276.5,260.5,2.68K,5.57,21370.0

In [148]:
gold.head(5)

  standard_time    mua    ban  price_mean
0    2015-01-01  34.95  35.15       35.05
1    2015-01-04  35.12  35.20       35.16
2    2015-01-06  34.87  34.93       34.90
3    2015-01-07  34.34  34.42       34.38
4    2015-01-08  32.98  33.12       33.05

In [149]:
btc_usd = btc_usd.merge(vni[['Ngày', 'Lần cuối']], on='Ngày', how='left', suffixes=('', '_vni'))

In [150]:
btc_usd.head(5)

,Ngày,Lần cuối,Mở,Cao,Thấp,KL,% Thay đổi,Lần cuối_USD_VND,Lần cuối_vni
0,2015-01-01,313.9,317.5,317.5,312.9,0.93K,-0.99,21370.0,NaN
1,2015-01-02,315.1,313.6,316.0,313.0,1.32K,0.40,21370.0,NaN
2,2015-01-03,282.0,314.8,314.8,282.0,1.30K,-10.51,NaN,NaN
3,2015-01-04,258.8,282.0,288.9,258.8,2.38K,-8.23,NaN,NaN
4,2015-01-05,273.2,261.0,276.5,260.5,2.68K,5.57,21370.0,544.45

In [151]:
btc_usd = btc_usd.merge(gold[['standard_time', 'price_mean']], left_on='Ngày', right_on='standard_time', how='left', suffixes=('', '_gold'))

In [111]:
btc_usd.head(5)

,Ngày,Lần cuối,Mở,Cao,Thấp,KL,% Thay đổi,Lần cuối_USD_VND,Lần cuối_vni,standard_time,price_mean
0,2015-01-01,313.9,317.5,317.5,312.9,0.93K,-0.99,21370.0,NaN,2015-01-01,35.05
1,2015-01-02,315.1,313.6,316.0,313.0,1.32K,0.40,21370.0,NaN,NaT,NaN
2,2015-01-03,282.0,314.8,314.8,282.0,1.30K,-10.51,NaN,NaN,NaT,NaN
3,2015-01-04,258.8,282.0,288.9,258.8,2.38K,-8.23,NaN,NaN,2015-01-04,35.16
4,2015-01-05,273.2,261.0,276.5,260.5,2.68K,5.57,21370.0,544.45,NaT,NaN

In [152]:
# rename columns for clarity
btc_usd.rename(columns={'Lần cuối': 'BTC_USD', 'Lần cuối_vni': 'VN_Index', 'Lần cuối_USD_VND': 'USD_VND', 'price_mean': 'Gold_Price'}, inplace=True)

In [153]:
# drop redundant columns
btc_usd.drop(columns=['Mở', 'Cao', 'Thấp', 'KL', '% Thay đổi'], inplace=True)

In [154]:
btc_usd

           Ngày   BTC_USD  USD_VND  VN_Index standard_time  Gold_Price
0    2015-01-01     313.9  21370.0       NaN    2015-01-01       35.05
1    2015-01-02     315.1  21370.0       NaN           NaT         NaN
2    2015-01-03     282.0      NaN       NaN           NaT         NaN
3    2015-01-04     258.8      NaN       NaN    2015-01-04       35.16
4    2015-01-05     273.2  21370.0    544.45           NaT         NaN
...         ...       ...      ...       ...           ...         ...
4060 2026-02-14   69825.0      NaN       NaN           NaT         NaN
4061        NaT       NaN      NaN       NaN           NaT         NaN
4062        NaT       NaN  26457.0       NaN           NaT         NaN
4063        NaT  126110.0      NaN       NaN           NaT         NaN
4064        NaT  126110.0  26457.0       NaN           NaT         NaN

[4065 rows x 6 columns]

In [155]:
btc_usd.to_csv(r'..\data\market_daily.csv', index=False)